#include "fs/vfs.h"
#include "fs/tmpfs.h"
#include "gnu_utils/string.h"

// Note: Ensure kprintf is available in your includes
extern void kprintf(const char* format, ...);

// ==========================================
// Global Variables Definition
// ==========================================
VFSNode* vfs_root = nullptr;
VFSNode* vfs_current_dir = nullptr;
char vfs_current_path[4096];
char vfs_display_path[4096];

// The display name of the root directory (Used ONLY for frontend printing)
const char* vfs_root_display_name = "root";


// ==========================================
// VFS Initialization
// ==========================================
void init_vfs() {
    kprintf("[VFS] Initializing Virtual File System...\n");

    // Clear the path buffer securely
    strinit(vfs_current_path, 4096);

    // 1. Create the root directory using the BACKEND standard ("/")
    // DO NOT use vfs_root_display_name here, the system needs the slash!
    vfs_root = new TmpFSDirectory("/");

    // Early return/Panic: Kernel Out of Memory
    if (vfs_root == nullptr) {
        kprintf("[VFS] PANIC: Failed to create root directory!\n");
        while(1); // Halt the system
    }

    // 2. Set the Current Working Directory to root
    vfs_current_dir = vfs_root;

    // 3. Initialize the backend path string to standard POSIX root ("/")
    strcpy(vfs_current_path, "/");

    kprintf("[VFS] Root filesystem mounted successfully.\n");
}

// ==========================================
// Path Resolution
// ==========================================
void vfs_resolve_path(const char* input_path, char* output_path) {
    // Early return: invalid pointers
    if (input_path == nullptr || output_path == nullptr) return;

    char work_buffer[4352];
    int w_idx = 0;

    // If path is relative (doesn't start with '/'), prepend the current working directory
    if (input_path[0] != '/') {
        for (int i = 0; vfs_current_path[i] != '\0'; i++) {
            work_buffer[w_idx++] = vfs_current_path[i];
        }
        // Ensure there is a trailing slash before appending the new part
        if (w_idx > 0 && work_buffer[w_idx - 1] != '/') {
            work_buffer[w_idx++] = '/';
        }
    }

    // Append the input path provided by the user
    for (int i = 0; input_path[i] != '\0'; i++) {
        work_buffer[w_idx++] = input_path[i];
    }
    work_buffer[w_idx] = '\0';

    // Stack to keep track of valid directory levels (max 32 levels deep)
    char stack[32][64]; 
    int top = 0;

    // Tokenize the dirty path using '/'
    char* token = strtok(work_buffer, "/");
    while (token != nullptr) {
        if (strcmp(token, ".") == 0) {
            // Do nothing, stay in current directory
        } else if (strcmp(token, "..") == 0) {
            // Go back one level (pop from stack)
            if (top > 0) top--;
        } else if (token[0] != '\0') {
            // Go down one level (push to stack)
            strcpy(stack[top], token);
            top++;
        }
        token = strtok(nullptr, "/");
    }

    // Reconstruct the clean absolute path
    output_path[0] = '/';
    output_path[1] = '\0';
    int out_idx = 1;

    for (int i = 0; i < top; i++) {
        for (int j = 0; stack[i][j] != '\0'; j++) {
            output_path[out_idx++] = stack[i][j];
        }
        // Add a slash between elements, but not at the very end
        if (i < top - 1) {
            output_path[out_idx++] = '/';
        }
    }
    output_path[out_idx] = '\0';
}

// ==========================================
// Node Traversal
// ==========================================
VFSNode* vfs_get_node_by_path(const char* absolute_path) {
    // Early return: safety checks
    if (absolute_path == nullptr || vfs_root == nullptr) return nullptr;

    // Early return: if it's just the backend root directory
    // We check against "/" here because absolute_path is generated by vfs_resolve_path
    if (strcmp(absolute_path, "/") == 0) return vfs_root;

    // strtok destroys the string, so we must make a local copy
    char path_copy[256];
    strcpy(path_copy, absolute_path);

    VFSNode* current = vfs_root;
    char* token = strtok(path_copy, "/");

    // Walk down the tree one folder at a time
    while (token != nullptr) {
        // Early return: If current node is a file, we can't go deeper
        if (current->flags != VFS_DIRECTORY) return nullptr;

        current = current->finddir(token);

        // Early return: The requested folder/file does not exist here
        if (current == nullptr) return nullptr;

        token = strtok(nullptr, "/");
    }

    return current;
}

// ==========================================
// Frontend Display Path Formatting
// ==========================================
void vfs_get_display_path(char* output_buffer) {
    // Early return: safety check
    if (output_buffer == nullptr) return;

    // 1. Start with the root display name (e.g., "root")
    strcpy(output_buffer, vfs_root_display_name);

    // 2. Early return: if we are exactly at the backend root "/", 
    // we just want "root", so we are done.
    if (strcmp(vfs_current_path, "/") == 0) return;

    // 3. If we are in a subdirectory (e.g., "/a"), vfs_current_path starts with '/'.
    // We append it directly to "root". 
    // Result: "root" + "/a" = "root/a"
    size_t root_len = strlen(vfs_root_display_name);
    strcpy(output_buffer + root_len, vfs_current_path);
}



void vfs_print_prompt() {
    // Local buffer for the formatted path (PATH_MAX + prefix size)
    char display_path[4352]; 
    
    // Format the path
    vfs_get_display_path(display_path);
    
    // Print the final result to the terminal
    kprintf("%s>", display_path);
}